### PR TITLE
[I-2]

### LINKED ISSUE #2: Configure Kubernetes API server to use TLS
Blocked by #1 

`kube-apiserver` should be configured with the appropriate flags to enable TLS.
The command line reference can be found here:

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

### PR DESCRIPTION
**Pull request by goshlanguage**
Fixes #2.

In this PR, I update the apiserver to set the correct cert and port. 

I also broke out the entrypoint from the `docker-compose.yml` file so that it can be more readable, since there are so many flags that are necessary.

One of note is the admission controllers configuration flag, which has the 7 of the 12 default admissions controllers configured. 

I changed the port to port 6443 so we can curl and otherwise access the apiserver over the secured protocol.

### CODE REVIEW

**Comment by goshlanguage** [comment]
@jrdelarosa8 what do you think? Everything look good?

**Review by jrdelarosa8 — CHANGES_REQUESTED** [review]
The only thing that I see is that we can update the to-do from `README.md` since that was addressed by I-1.

**Review by jrdelarosa8 — APPROVED** [review]

**Comment by goshlanguage** [comment]
I've updated various bits of documentation to reflect the changes in this PR. I *think* this should cover things, but do you think it makes sense now @jrdelarosa8 ?

**Comment by jrdelarosa8** [comment]
LGTM, ship it

**Pull request merged**
